name: testCICD

on:
  push:
    branches: [main]
    paths:
      - .github/workflows/**

permissions:
  contents: read
  packages: write
  issues: write
  pull-requests: write

jobs:
  Print_ENV:
    name: Print ENV
    runs-on: ubuntu-latest
    steps:
      - run: env
      - run: exit 0
    