name: testCICD
on:
  push:
    branches: [main]
    paths:
      - .github/workflows/**

permissions:
  contents: read
  packages: write
  issues: write
  pull-requests: write

jobs:
  Print_ENV:
    name: Print ENV
    runs-on: ubuntu-latest
    steps:
      - run: env
  React_Build:
    name: Building React App
    needs: [Print_ENV]
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        working-directory: react-app
        run: npm install

      - name: Build React app
        working-directory: react-app
        run: npm run build

      - name: List contents of root directory
        run: ls -R

      - name: Create artifact
        uses: actions/upload-artifact@v2
        with:
          name: react-app
          path: react-app/build/